name: CI Build for Docker Action
on:
  push:
    branches: [ main ]
    paths: [ actions/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run my own container action
        id: hello-action
        uses: ./actions/hello-world-docker
        with:
          who-to-greet: 'Mr. Miyagi'

      - name: Output time set in the container
        run: echo "Tiden var ${{ steps.hello-action.outputs.time }} when the action said hello"
