name: Resusable Workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: "Tjena på vem"
        type: string
        required: true
        default: World
    outputs:
      current-time:
        description: "När sa du tjena"
        value: ${{ jobs.reusable-job.outputs.current-time }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet someone
        run: echo "Tjena ${{ inputs.who-to-greet }}"
      - name: Current time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
    outputs:
      current-time: ${{ steps.time.outputs.time }}
        
      
